resources: git: fix configuration with older git versions.
Without that fix we have the following build error on PureOS 10
(byzantium):

    Submodule path 'util/nvidia/cbootimage': checked out
    '65a6d94dd5f442578551e0a81ecbe5235e673fd4'
    Committer identity unknown

    *** Please tell me who you are.

    Run

      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"

    to set your account's default identity.
    Omit --global to set the identity only in this repository.

    fatal: unable to auto-detect email address (got '[...]')
    ERROR: download/coreboot: Unable to apply patch
    '../../resources/coreboot/default/patches/0001-apple-macbook21-Set-default-VRAM-to-64MiB-instead-of.patch'
    for board 'default' on tree 'default'Committer identity unknown

This is because PureOS 10 (byzantium) has git 2.30.2 and in PureOS,
and since 'man git' doesn't show GIT_CONFIG_GLOBAL nor
GIT_CONFIG_SYSTEM, git 2.30.2 doesn't understand these variables.

Since git already has -c option, we use that instead.

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
Acked-by: Adrien 'neox' Bourmault <neox@gnu.org>