packages: descriptors: ich9utils: workaround failed fetch.
Without that workaround we have:
    $ make release
    [...]
    Trying to download from Software Heritage...
    SWH: found revision 53749b0c6f7c5778bdd1ec2b91cd230626752579 with
         directory at 'https://archive.softwareheritage.org/api/1/d'
    SWH: object
         swh:1:dir:73a4f366101afefb4dd8dddbaf9d0221af7d6a9f
         could not be fetched from the vault
    builder for
        `/gnu/store/yzvpv2fbg3wbnzniimxn6sc14230z2by-coreboot-0-checkout.drv'
        failed to produce output path `/gnu/store/'
    build of
        /gnu/store/yzvpv2fbg3wbnzniimxn6sc14230z2by-coreboot-0-checkout.drv
        failed
    View build log at
        '/var/log/guix/drvs/yz/vpv2fbg3wbnzniimxn6sc14230z2by-coreboot-0-checkout.drv.bz2'.
    cannot build derivation
        `/gnu/store/cq6mqhna9qppjpm9ld78a60xn1xdgh0y-ich9utils-0.drv':
        1 dependencies couldn't be built
    guix build: error: build of
        `/gnu/store/cq6mqhna9qppjpm9ld78a60xn1xdgh0y-ich9utils-0.drv' failed
    Error: build/roms: something went wrong
    make: *** [Makefile:925: release] Error 1

I tried several times and the fetch always failed. So the issue is
probably easily reproductible.

If I try to download the repository manually in Trisquel and it works:
    $ guix repl
    scheme@(guix-user) [1]> ,use (guix git)
    scheme@(guix-user) [3]> (define clone-from-swh
    (@@ (guix git) clone-from-swh))
    scheme@(guix-user) [3]> (clone-from-swh
    "https://notabug.org/libreboot/ich9utils.git"
    "53749b0c6f7c5778bdd1ec2b91cd230626752579"
    "tmp.git")
    SWH: found revision 53749b0c6f7c5778bdd1ec2b91cd230626752579
         with directory at
         'https://archive.softwareheritage.org/api/1/directory/73a4f366101afefb4dd8dddbaf9d0221af7d6a9f/'
    SWH vault: requested bundle cooking, waiting for completion...
    swh:1:rev:53749b0c6f7c5778bdd1ec2b91cd230626752579.git/
    swh:1:rev:53749b0c6f7c5778bdd1ec2b91cd230626752579.git/HEAD
    [...]
    $1 = #<git-repository 12a914f0>

This is with the Guix daemon from Trisquel 11 (aramo) and
Guix c12e28dfc0e2a8013b6ba0b89cb23cfa0bb9c5f2.

So we workaround by changing the URL for now.

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>